sudo: required
dist: trusty

env:
  - BLLIPINTERFACE=cmd
  - BLLIPINTERFACE=python

language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y libboost-dev liblbfgs-dev flex
  - bash -c "[ $BLLIPINTERFACE != "python" ] || sudo apt-get install -y swig3.0 python-nose"
  - bash -c "[ $BLLIPINTERFACE != "python" ] || sudo pip install python-coveralls tox flake8 nltk asciitree"
before_script:
  - bash -c "[ $BLLIPINTERFACE != "python" ] || swig3.0 -version"
script:
  - bash -c "[ $BLLIPINTERFACE != "cmd" ]    || make world"
  - bash -c "[ $BLLIPINTERFACE != "cmd" ]    || ./regression-test -fFtT"
  - bash -c "[ $BLLIPINTERFACE != "python" ] || tox"
after_success:
  - bash -c "[ $BLLIPINTERFACE != "python" ] || coveralls"
